project:
  type: book
  output-dir: "_build"
  preview:
    port: 4567
    browser: true

# https://quarto.org/docs/books/
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "FLR MSE"
  author: "FLR Team"
  date: "last-modified" # "7/24/2024"
  date-format: "iso"
  #doi: "...."
  #isbn: "..."
  #issn: "..."
  #edition: "v2"

  site-url: https://flrproject.org/book
  repo-url: https://github.com/flr/book
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub, docx]

  # https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph: true

  # https://quarto.org/docs/reference/projects/books.html#search
  search: true
    #location: sidebar # navbar, sidebar
    #type: textbox # overlay, textbox

  cover-image: images/cover.png
  #favicon: images/favicon.ico

  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  sidebar:
    logo: images/ospo-logo.png


  chapters:
    - index.qmd
#    - introduction.qmd
#    - simple_example.qmd
#    - operating_models.qmd
#    - observations_error.qmd
#    - estimators.qmd
    - harvest_control_rules.qmd
#    - implementation_systems.qmd
#    - other_steps.qmd
#    - implementation_error.qmd
#    - running_mse.qmd
#    - analyzing_results.qmd
#    - developing_modules.qmd

    #- part: "Part
    #  #href:  part/index.qmd
    #  chapters:
    #    - part/chap-3.qmd
    #    - part/chap-4.qmd

    - references.qmd

    - "-------------"

  appendices:
    - appendix.qmd

  # shows up at bottom of page
  #body-footer: "&copy; Copyright 2024, Your Name Here"

  page-footer:
    center: |
      <p>&copy; Copyright 2026, GWU Open Source Program Office (OSPO)</p>

bibliography: references.bib

execute: 
  cache: true

format:
  html:
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light: default #flatly
      dark: darkly
    css: styles.css

  pdf:
    documentclass: scrreprt
